{% set version = "1.1.0" %}

package:
  name: python-wasmer-split
  version: {{ version }}

source:
  - url: https://github.com/wasmerio/wasmer-python/archive/refs/tags/{{ version }}.tar.gz
    sha256: 220af5b2675480daea4ebc1cede45728ce1b270cdc141ebff08ef0870cc23cfd

build:
  number: 1
  skip: true  # [py<38]

outputs:
  - name: python-wasmer
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]
    build:
      run_exports:
        - python-wasmer
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - sysroot_linux-64 2.17  # [linux64]
        - cargo-bundle-licenses

      host:
        - python
        - pip
        - maturin
        - lld
        - pytest

      run:
        - python
        - lld

    test:
      imports:
        - wasmer


  - name: python-wasmer-compiler-cranelift
    version: {{ version }}
    script: build_wasmer.sh  # [unix]
    script: build_wasmer.bat  # [win]

    build:
      ignore_run_exports:
         - python-wasmer

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses

      host:
        - python
        - pip
        - maturin
        - pytest
        - pytest-benchmark
        - python-wasmer

      run:
        - python-wasmer
        - python

    test:
      imports:
        - wasmer_compiler_cranelift


  - name: python-wasmer-compiler-singlepass
    version: {{ version }}
    script: build_wasmer.sh  # [unix]

    build:
      skip: true  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses


      host:
        - python
        - pip
        - maturin
        - pytest
        - python-wasmer

      run:
        - python-wasmer
        - python

    test:
      imports:
        - wasmer_compiler_singlepass  # [unix]


  - name: python-wasmer-compiler-llvm
    version: {{ version }}
    script: build_wasmer.sh  # [unix]

    build:
      skip: true  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('rust') }}
        - cargo-bundle-licenses

      host:
        - python
        - pip
        - maturin
        - pytest
        - pytest-benchmark
        - clang
        - llvmdev
        - python-wasmer
        - python-wasmer-compiler-cranelift

      run:
        - clang
        - libzlib
        - libffi
        - libstdcxx-ng  # [linux64]
        - python-wasmer
        - python

    test:
      imports:
        - wasmer_compiler_llvm  # [unix]


about:
  home: https://wasmer.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebAssembly runtime for Python
  description: "Wasmer is a fast and secure WebAssembly runtime that enables super lightweight containers to run anywhere: from Desktop to the Cloud, Edge and IoT devices."
  doc_url: https://docs.wasmer.io
  dev_url: https://github.com/wasmerio/wasmer
  doc_source_url: https://github.com/wasmerio/wasmer/tree/master/docs
  license_url: https://github.com/wasmerio/wasmer/blob/master/LICENSE
  

extra:
  skip-lints:
    - missing_tests
  feedstock-name: python-wasmer-split
  recipe-maintainers:
    - atrawog
    - wolfv
    - bollwyvl
